### ISSUE TITLE
Template directory being referenced incorrectly

### ISSUE THREAD

**Issue by Dolondro** [silktide/lazy-boy#7]
Steps to reproduce:
Require lazy-boy
Require symfony-console

Throws error:

  [Silktide\LazyBoy\Exception\InstallationException]        
  The template file '/app/console.php.temp' does not exist

**Comment by downsider** [comment]
This is due to composer using eval to load in the ScriptController plugin, destroying the reference to the script's file location

Fixed in v2.0.4
